[project]
name = 'GreenEnergy'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.GreenEnergy]
path = 'contracts/GreenEnergy.clar'
clarity_version = 3
epoch = 3.1

[contracts.CreditVerification]
path = 'contracts/CreditVerification.clar'
clarity_version = 3
epoch = 3.1

[contracts.CreditRetirement]
path = 'contracts/CreditRetirement.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
